# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 00:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapPickle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('data', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/uploads'), upload_to=b'')),
            ],
        ),
    ]
