# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snappickle',
            name='data',
        ),
        migrations.AddField(
            model_name='snappickle',
            name='pickleFileName',
            field=models.FilePathField(default=b'', match=b'*.pkl'),
        ),
        migrations.AddField(
            model_name='snappickle',
            name='snapFileName',
            field=models.FilePathField(default=b'', match=b'*.graph'),
        ),
    ]
