# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import snapData.validators


class Migration(migrations.Migration):

    dependencies = [
        ('snapData', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=b'zipFiles/', validators=[snapData.validators.validate_file_extension]),
        ),
    ]
