# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapData', '0009_auto_20180501_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='name',
        ),
    ]
