# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 00:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapData', '0012_auto_20180506_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='snappickle',
            name='networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=[], size=None),
            preserve_default=False,
        ),
    ]
