# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 02:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapData', '0013_snappickle_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='snappickle',
            name='onestop_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='snappickle',
            name='networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=list, size=None),
        ),
    ]
