# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapData', '0014_auto_20180604_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='onestop_id',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
